### ISSUE TITLE
Manually update tle doesn't work

### ISSUE THREAD

**Issue by KiwiInNZ** [Xerbo/satmap#4]
> pi@alpha:~/pmap $ ./main.py -u
> from: too many arguments

hangs

> ^C
> ^Cfrom: too many arguments
> from: too many arguments
> from: too many arguments
> ./main.py: line 8: syntax error near unexpected token `('
> ./main.py: line 8: `parser = argparse.ArgumentParser()'

**Comment by Xerbo** [comment]
While this should work, it most definitely is not the proper way to do it. Although a manual TLE update should not be necessary since TLE's are automatically managed (and updated).

**Comment by KiwiInNZ** [comment]
Probably something to be added to the documentation once written as something which shouldn't be needed. Although if the argument is there then it should work.
