### ISSUE TITLE
Install requirements - ModuleNotFoundError: No module named 'Cython'

### ISSUE THREAD

**Issue by KiwiInNZ** [Xerbo/satmap#5]
Using fully patched Raspian Buster:

sudo pip3 install -r requirements.txt
[sudo] password for pi:
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/SciTools/cartopy.git@v0.18.0 (from -r requirements.txt (line 5))
  Cloning https://github.com/SciTools/cartopy.git (to revision v0.18.0) to /tmp/pip-req-build-mzgyq1p9
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-mzgyq1p9/setup.py", line 34, in <module>
        import Cython
    ModuleNotFoundError: No module named 'Cython'

Installing the contents of the requirements.txt file on a line by line basis - numpy, scipy and orbit_predictor install cleanly.

sudo pip3 install git+https://github.com/SciTools/cartopy.git@v0.18.0:

sudo pip3 install git+https://github.com/SciTools/cartopy.git@v0.18.0
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/SciTools/cartopy.git@v0.18.0
  Cloning https://github.com/SciTools/cartopy.git (to revision v0.18.0) to /tmp/pip-req-build-_404y6th
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-_404y6th/setup.py", line 34, in <module>
        import Cython
    ModuleNotFoundError: No module named 'Cython'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-_404y6th/

https://github.com/SciTools/cartopy/issues/725

> I have to manually install cython on the same virtualenv:
> 
> pip install cython

Trying to install this first then gives error:

sudo pip3 install cython
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting cython
  Downloading https://files.pythonhosted.org/packages/ba/b7/00ef671f74ee4694de58d88101e6f9a655cb8009e37a66a57f19642ff5d6/Cython-0.29.19-py2.py3-none-any.whl (971kB)
    100% |████████████████████████████████| 972kB 442kB/s
Installing collected packages: cython
Successfully installed cython-0.29.19
pi@alpha:~/pmap $ sudo pip3 install git+https://github.com/SciTools/cartopy.git@v0.18.0
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/SciTools/cartopy.git@v0.18.0
  Cloning https://github.com/SciTools/cartopy.git (to revision v0.18.0) to /tmp/pip-req-build-477xp5g1
    Complete output from command python setup.py egg_info:
    /tmp/pip-req-build-477xp5g1/setup.py:107: UserWarning: Unable to determine GEOS version. Ensure you have 3.3.3 or later installed, or installation may fail.
      '.'.join(str(v) for v in GEOS_MIN_VERSION), ))
    Proj 4.9.0 must be installed.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-477xp5g1/

Installing this - sudo pip3 install goes:

sudo pip3 install goes
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting goes
  Downloading https://files.pythonhosted.org/packages/f4/98/71c1bc4512726783c6551be215ba15e91b4644ba09851b3366278e180be6/GOES-0.0.2-py3-none-any.whl
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from goes) (1.16.2)
Collecting s3fs (from goes)
  Downloading https://files.pythonhosted.org/packages/b8/e4/b8fc59248399d2482b39340ec9be4bb2493846ac23641b43115a7e5cd675/s3fs-0.4.2-py3-none-any.whl
Collecting pyproj (from goes)
  Downloading https://files.pythonhosted.org/packages/a8/f9/e7876096af700e7987f5e5abffa09b783ab31157083f76cd88c83e3dbe95/pyproj-2.6.1.post1.tar.gz (545kB)
    100% |████████████████████████████████| 552kB 699kB/s
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    proj executable not found. Please set the PROJ_DIR variable.For more information see: https://pyproj4.github.io/pyproj/stable/installation.html

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-a0u4ol3g/pyproj/

https://pyproj4.github.io/pyproj/stable/installation.html
https://github.com/pyproj4/pyproj/issues/582

sudo pip3 install pyproj 

sudo pip3 install proj-util
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting proj-util
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/proj-util/

https://pypi.org/simple/proj-util/

> 404 Not Found

**Comment by KiwiInNZ** [comment]
There seems to be issue(s) with the dependencies, needing at least the addition of cython, plus resolving the other issue linked to proj-util.

**Comment by Xerbo** [comment]
I forgot how much of a mess Cartopy is to install, its also kinda slow. So I think I'm just going to drop it for something else (it haven't even finished the interface for it, so its not even in use).

Just remove the `git+https://github.com/SciTools/cartopy.git@v0.18.0` line from `requirements.txt` or run `git pull` if you cloned with git.
